def code
pipeline {
    agent any
    stages {
        stage('Load groovy') {
            steps {
                script {
                    code = load 'vars/helloworld.groovy'
                    code.test2()
                }
            }

        }
    }
}